### ISSUE TITLE
Node 13 request.connection deprecated

### ISSUE THREAD

**Issue by JohanCodinha** [articulate/paperplane#55]
On file paperplane/lib/parseUrl.js 
at line 19: `req.connection.encrypted ? 'https' : 'http'`

[Node http request docs](https://nodejs.org/api/http.html#http_request_connection)

**Comment by JohanCodinha** [comment]
Tested the fix on Node 13 and when using http.createServer the encrypted key on req.socket is undefined.
I did not try when the server is started with https.createServer.
Also I could not find documentation on socket.encrypted.

**Comment by flintinatux** [comment]
@JohanCodinha, first of all, thanks for making an issue for this, because I was unaware that was deprecated!

From what I can tell, `req.socket.encrypted` is `undefined` normally (because it is never set), but is `true` for TLS connections.  You would need to start the server with `https.createServer` to see that behavior.  Here's what I found in the docs for `tlsSocket.encrypted`: 
 https://devdocs.io/node/tls#tls_tlssocket_encrypted

**Comment by JohanCodinha** [comment]
Well thanks for explaining it, it make sense now.
I'm using paperplane and enjoying it so perfectly normal that I notified you.
